# Generated by Django 6.0 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_delivery_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                choices=[
                    ("home_delivery", "Home delivery (within 10 km of Gota; free; minimum order ₹500)"),
                    ("porter", "Porter (within Ahmedabad; chargeable)"),
                    ("courier", "Courier (within India; chargeable)"),
                ],
                default="porter",
                max_length=20,
            ),
        ),
    ]
