# Generated by Django 6.0

from django.db import migrations, models
import django.db.models.deletion
import cloudinary.models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_available_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
